### ISSUE TITLE
lottery on dogechain

### ISSUE THREAD

**Issue by leyr1112** [leyr1112/unidoge-sdk#2]
How can i get non-predictable random number on dogechain

**Comment by hodler-smart** [comment]
You can use RNG on other chain but on dogechain you cant make it in fact.
But you can make RNG in manually.
You can refer this link.
https://blog.finxter.com/how-to-generate-random-numbers-in-solidity/

**Comment by ghost** [comment]
You cant get absolutely random number on blockchain it self, and you should third party like Chainlink.
I know Chainlink didnt propagate to dogechain yet, but you can get help from support team.
